//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowCompanyApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public orders()
        {
            this.order_items = new HashSet<order_items>();
        }
    
        public int id { get; set; }
        public int client_id { get; set; }
        public int manager_id { get; set; }
        public Nullable<int> surveyor_id { get; set; }
        public Nullable<int> installer_id { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public Nullable<System.DateTime> planned_install_date { get; set; }
        public Nullable<System.DateTime> actual_install_date { get; set; }
        public decimal total_price { get; set; }
        public Nullable<int> status_id { get; set; }
        public string comment { get; set; }
    
        public virtual clients clients { get; set; }
        public virtual employees employees { get; set; }
        public virtual employees employees1 { get; set; }
        public virtual employees employees2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_items> order_items { get; set; }
        public virtual order_statuses order_statuses { get; set; }
    }
}
